### ISSUE TITLE
Nilearn: Machine learning for Neuro-Imaging in Python

### ISSUE THREAD

**Issue by jeromedockes** [ohbm/OpenScienceRoom2019#16]
**Title**

Nilearn: Machine learning for Neuro-Imaging in Python

**Presentor and Affiliation**

Jérôme Dockès, INRIA

**Collaborators**

Nilearn is developped by a growing international community:
https://github.com/nilearn/nilearn/graphs/contributors.

**Github Link (if applicable)**

https://github.com/nilearn/nilearn
https://nilearn.github.io/

**Abstract (max. 200 words):**

Nilearn is a pure Python library for applications of statistical analysis and
machine learning methods to neuroimaging. It provides efficient, well documented
and tested tools for image manipulation, decomposition methods and functional
connectivity, supervised learning and decoding, and publication-quality or
interactive plotting. It also provides utilities to download neuroimaging
datasets and comes with a wide gallery of examples. With Nilearn, applying
powerful and well-established machine learning methods to neuroimaging data
is easy and reproducible.

A lot has changed since OHBM 2018: new features such as the ReNA
method for creating fast brain parcellations, interactive plots to
visualize brain images in a web browser, and new dataset downloaders.
We also improved the documentation and added new didactic examples.

The Open Science Room is the perfect venue for Nilearn users and contributors to
meet, and we would like to demo Nilearn's core functionality and recently added
features.

**Preferred Session**

3. Demo: New advances in open neuroimaging methods

**Additional Context**

**Comment by TimVanMourik** [comment]
Hi @jeromedockes, I’m happy to tell you that we’d like to host your presentation as a lightning talk in the OSR in the **Machine learning in Neuroscience** session. This will be a talk of 5 minutes + 5 minutes of questions. We decided to rebrand one session of lightning talks to a machine learning theme as a result of many applications around this theme. We cannot give you a slot in your preferred session due to the very high number of applications. 

We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by jeromedockes** [comment]
thanks! I'll open a PR as soon as I have something ready

**Comment by TimVanMourik** [comment]
Thanks for the presentation!

Presentation uploaded in #52!
