### ISSUE TITLE
Community discussion: BEP001 (BIDS extension for multi-contrast structural acquisitions)

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceRoom2019#18]
**Topic**: Community discussion for anyone interested in BIDS extension proposal 001: Structural acquisitions that include multiple contrasts

**Main organiser**: @Gilles86 & @KirstieJane 

**Preferred time slots**: None (we haven't looked at our schedules yet!)

**Tag other attendees**: @christophephillips, @lazaral (more to come!)

**Open to all?**: Yes :smiley_cat: 

**Additional Context**: BEP001 is working to extend the brain imaging data structure (BIDS) to better accomodate quantiative structural imaging. You can see their work at https://github.com/bids-standard/bep001. The team are hoping to have a proposal ready for broader community feedback by this meeting in the OSR. If you're interested in using structural data in BIDS format or if you know a lot about the BIDS ecosystem and can spot where conflicts with the current standard may appear, we would be particularly interested in having you join the discussion 💖 

#

Bookings will be coordinated by @TimVanMourik. The schedule is available [here](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Comment by ChristophePhillips** [comment]
Yeah, keep me informed when you know the date-time of the meeting.
Moreover @mfcallaghan could be joining us too.

**Comment by TimVanMourik** [comment]
Hi @raamana, basically Monday morning and Wednesday afternoon are completely free. How about Monday 11:00?

**Comment by ChristophePhillips** [comment]
Monday 11:00 sounds good to me but @Gilles86 and @KirstieJane may want their word heard. :-)

**Comment by Gilles86** [comment]
Yes, great.

**Comment by KirstieJane** [comment]
Hey @TimVanMourik - I guess this wasn’t scheduled because you were waiting for me? Can we move to Wednesday?

**Comment by TimVanMourik** [comment]
Aahh, sorry, yes, I should have sent a reminder! :O I’m afraid the Wednesday slot filled up by now. Any white space in the calendar is still available. PIck your time!

**Comment by KirstieJane** [comment]
@ChristophePhillips & @Gilles86 - can you meet at lunch (12noon) on Wed or Thurs?

**Comment by Gilles86** [comment]
Hmm. I give a software demonstration on Wednesday at 12.45, which I also
have to prepare a bit Bit earlier would work. Otherwise Thursday.

**Comment by TimVanMourik** [comment]
So the OSR is not completely dedicated and reserved for this, but the hack area is of course big enough to have your meeting anyway. Sorry for screwing up here! I’m happy to put it on the schedule for another time if you want of course.

**Comment by KirstieJane** [comment]
Lunch on Thursday could work, right? lets put it in for 12 noon then please @TimVanMourik

**Comment by TimVanMourik** [comment]
Done!

**Comment by ChristophePhillips** [comment]
Yes. Ok for me on Thursday noon. :-)Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Kirstie Whitaker <notifications@github.com> Date : 10/06/19  10:09  (GMT+01:00) À : ohbm/OpenScienceRoom2019 <OpenScienceRoom2019@noreply.github.com> Cc : Christophe Phillips <c.phillips@uliege.be>, Mention <mention@noreply.github.com> Objet : Re: [ohbm/OpenScienceRoom2019] Community discussion: BEP001 (BIDS extension for multi-contrast structural acquisitions) (#18) Lunch on Thursday could work, right? lets put it in for 12 noon then please @TimVanMourik

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ohbm/OpenScienceRoom2019/issues/18?email_source=notifications\u0026email_token=AAPLGHROZXMVQK2BRUCKQ5DPZYD3DA5CNFSM4HNFPMPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJG7RA#issuecomment-500330436",
"url": "https://github.com/ohbm/OpenScienceRoom2019/issues/18?email_source=notifications\u0026email_token=AAPLGHROZXMVQK2BRUCKQ5DPZYD3DA5CNFSM4HNFPMPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJG7RA#issuecomment-500330436",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TimVanMourik** [comment]
Closing this discussion issue, but feel free to add more content, links, or documents (PR) to document what's been discussed!
