### ISSUE TITLE
APACE - Accelerated Permutation Inference for ACE models

### ISSUE THREAD

**Issue by xuchen312** [ohbm/OpenScienceRoom2019#20]
**Title**
APACE - Accelerated Permutation Inference for ACE models

**Presentor and Affiliation**
Xu Chen, Leiden University Medical Centre (@xuchen312)

**Collaborators**
Thomas Nichols, Oxford University (@nicholst; PI of this project)

**Github Link (if applicable)**
[APACE](https://github.com/NISOx-BDI/APACE)

**Abstract (max. 200 words):**
There are a wealth of tools for fitting linear models at each location in the brain in neuroimaging analysis, and a wealth of genetic tools for estimating heritability for a small number of phenotypes. But there remains a need for computationally efficient neuroimaging genetic tools that can conduct analyses at the brain-wide scale. 

The ''Accelerated Permutation inference for ACE models (APACE)'' is an easily accessible matlab-based tool for fast heritability inference with twin data, which employs a simple non-iterative heritability estimation method that is comparable to existing methods, and provides 4 different optional inference approaches of voxel-wise, cluster-based, summary measure and aggregate heritability inferences. The users can easily select the desired inferences or implement all (the default). Permutation and bootstrapping analysis approaches are also included for computing p-values and confidence intervals, respectively.

**Preferred Session**
Oral sessions and demos - 3. Demo: New advances in open neuroimaging methods

**Additional Context**

**Comment by asoroosh** [comment]
I'd love to be there.

**Comment by TimVanMourik** [comment]
Hi @xuchen312, I’m happy to tell you that we’d like to host your presentation as a lightning talk in the OSR in the **Machine learning in Neuroscience** session. This will be a talk of 5 minutes + 5 minutes of questions. We decided to rebrand one session of lightning talks to a machine learning theme as a result of many applications around this theme. We cannot give you a slot in your preferred session due to the very high number of applications. 

We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.
