### ISSUE TITLE
ARIbrain - Valid circular inference for fMRI analysis

### ISSUE THREAD

**Issue by wdweeda** [ohbm/OpenScienceRoom2019#21]
Title
ARIbrain - Valid circular inference for fMRI analysis

Presentor and Affiliation
Wouter, Weeda, Leiden University (@wdweeda)
Xu Chen, Leiden University Medical Centre (@xuchen312)

Collaborators
Jelle Goeman, Leiden University Medical Centre
Jonathan Rosenblatt, University of the Negev
Livio Finos, University of Padua
Aldo Solari, University of Milan Bicocca 

Github Link (if applicable)
https://github.com/wdweeda/ARIbrain

Abstract (max. 200 words):
Analysis of fMRI data is often constrained to a strict set of procedures to avoid statistical pitfalls like double-dipping or increased false-positive rates. In practice this means that detected regions of activation can often not be analysed afterwards.

One of the solutions to this problem is the recently developed method All-resolutions inference (ARI) [1]. ARI allows researchers to estimate the proportion of truly active voxels within freely chosen regions-of-interest (ROIs). These ROIs can be chosen based on a priori defined regions (e.g. anatomical regions or meta-analysis locations), or on ROIs derived from the same data (e.g. cluster-forming thresholds, or data from other experimental conditions). All analyses can be performed as many times as a researcher wants with full family-wise error (FWE) control. 

This gives ARI almost unlimited freedom in analysing brain images. For example, researchers can use multiple thresholds within the same image or base analysis on activation data from the same experiment. In addition, researchers are allowed to ‘drill- down’ or zoom in within these ROIs, without losing FWE control. 

In this demonstration, we present the ARIbrain package. We will highlight the flexibility of the ARI framework and show how the ARI method can be used in analysis pipelines.

Preferred Session
Oral sessions and demos - 3. Demo: New advances in open neuroimaging methods

Additional Context
[1] Rosenblatt et al. 2018. All-resolutions Inference. Neuroimage

**Comment by TimVanMourik** [comment]
Hi @wdweeda, I’m happy to tell you that we’d like to host your presentation as a demo/tutorial in the OSR in the **From statistical to biological validity** session. This will be a talk of 20 minutes + 5 minutes of questions. We could unfortunately not assign you a slot in your preferred session due to the high number of applications. However, we would really like to give your method a platform in the OSR and feel that the different take on statistical inference is well-suited for the current session.

We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by TimVanMourik** [comment]
Just to connect y’all: @wdweeda, I think it would be impressively cool to see if this method could be implemented in @SNeuroble’s BrainSuite Web (#37)

**Comment by SNeuroble** [comment]
Awesome! Would love to stay in touch re this

**Comment by wdweeda** [comment]
Same here!

**Comment by TimVanMourik** [comment]
Cool! @wdweeda, do you think you could either send a Pull Request with your slides, or send them to me so that I can upload them?

**Comment by wdweeda** [comment]
@TimVanMourik, I've sent the pull request with the slides.
