### ISSUE TITLE
 fMRIDenoise: automated denoising strategies comparison and quality control of functional connectivity data

### ISSUE THREAD

**Issue by kfinc** [ohbm/OpenScienceRoom2019#22]
**Title**
fMRIDenoise: automated denoising strategies comparison and quality control of functional connectivity data

**Presentor and Affiliation**
Karolina Finc, Nicolaus Copernicus University (@kfinc)
Kamil Bonna, Nicolaus Copernicus University (@kbonna)

**Collaborators**
Mateusz Chojnowski, Nicolaus Copernicus University (@SiegfriedWagner)
Włodzisław Duch, Nicolaus Copernicus University
Oscar Esteban, Stanford University (@oesteban)
Rastko Ciric, Stanford University (@rciric)
Russ Poldrack, Stanford University (@poldrack)

**Github Link (if applicable)**
https://github.com/nbraingroup/fmridenoise

**Abstract (max. 200 words):**
Functional connectivity (FC) became a prominent method in functional MRI (fMRI) studies. After preprocessing of fMRI data, time-series should be denoised to minimize the effect of motion and physiological processes via regressing out potentially confounding variables. The great variability in the selection of denoising strategies by researchers, together with the lack of a standardized denoising procedure, makes comparisons between FC studies hardly possible.

We want to present an early version of the fMRIDenoise, a tool for automatic denoising, denoising strategies comparisons, and functional connectivity data quality control. FMRIDenoise is designed to work directly on fMRIPrep derivatives and data in BIDS standard. We believe that the tool can make the selection of the denoising strategy more objective and also help researchers to obtain FC quality control metrics with almost no effort. 

As the project is at an early stage of development, we would like to receive feedback from the community regarding its future development and discuss a standard for the description of the denoising strategies in .json files. We are also open to contributions.

**Preferred Session**
3. Demo: New advances in open neuroimaging methods

**Comment by emdupre** [comment]
Definitely interested in talking through this ! I'll be there :+1:

**Comment by TimVanMourik** [comment]
Hi @kfinc, I’m happy to tell you that we’d like to host your presentation as a lightning talk in the OSR in the **Machine learning in Neuroscience** session. This will be a talk of 5 minutes + 5 minutes of questions. We decided to rebrand one session of lightning talks to a machine learning theme as a result of many applications around this theme. We cannot give you a slot in your preferred session due to the very high number of applications. 

We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by TimVanMourik** [comment]
Thanks for the presentation!

Presentation uploaded in #51!
