### ISSUE TITLE
BIDS for magneto- and electro- physiology

### ISSUE THREAD

**Issue by CPernet** [ohbm/OpenScienceRoom2019#3]
**Brain Imaging Data Structure for MEEG**

_Chair_
**Cyril Pernet**

_We wish to have a round table with contributors and users to discuss BIDS for MEEG, possible improvement for the current specification, and discuss/present extensions for derived data_

**Session**
Monday AM 10.30

**Agenda**
- current specification usage for [MEG](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html) and [EEG](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html) any feedback welcome
- MEEG connectivity: should we have a single framework with [BEP017](https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit#heading=h.mqkmyp254xh6)
- [derivatives](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw), alignement with [common derivatives](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit) and hot topics

**Comment by ChristophePhillips** [comment]
Count me in.

**Comment by TimVanMourik** [comment]
I added this meeting to the [agenda](https://calendar.google.com/calendar/embed?src=jrc4huuqm892k5io979qvbc67o%40group.calendar.google.com&ctz=Europe%2FAmsterdam) for **Tuesday 16:00-17:00** (June 11th). Would that work?

**Comment by CPernet** [comment]
if there are distinct room, could I have that in parallel to demos on Monday? I don't want to miss Thomas keynote on Tuesday

**Comment by TimVanMourik** [comment]
The morning demos only start on Tuesday so Monday morning is fine! Pick your time.

**Comment by CPernet** [comment]
thank you - can we do 10.30? is there a place I post a little agenda thing

**Comment by TimVanMourik** [comment]
I added the meeting to the [calendar](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ). In the description I am currently pointing to this issue. Let me know if you'd like me to have it point to an agenda instead.

**Comment by CPernet** [comment]
great thx

**Comment by jasmainak** [comment]
Is it just me but I see the meeting on the calendar on Tuesday not Monday

**Comment by CPernet** [comment]
just you :-)

**Comment by sappelhoff** [comment]
I see it on Monday as well :-)

**Comment by jasmainak** [comment]
Hah, okay I figured it out. There are two MEG/EEG events so I was confused between the two

**Comment by TimVanMourik** [comment]
Ahh, sorry @jasmainak, I was under the impression I moved the meeting, but apparently I copied it. Thanks for spotting the mistake :)

**Comment by sappelhoff** [comment]
# Meeting notes

The meeting happened as planned. Below I summarize some points that were raised. Please add to this list in case I forgot/missed something (@CPernet also took some notes).

Also, **please tag other people who attended this meeting** and have a GitHub handle (but are not subscribed to this issue yet --> see in the top right of the Github website under "Participants").

@franklin-feingold @wmvanvliet

### agenda 1: General Feedback

1. "In our lab we want to format our data according to BIDS for *internal use only*. It would be convenient for us to use our file formats without converting them to the "accepted" EEG BIDS data formats."
    - Answer: "We cannot extend the list of accepted data formats in BIDS"
    - Follow up: "Could we extend the `bids-validator` to accept an optional flag in the command line, that  *non-BIDS-accepted* fle formats are validated (not ignored) ... but do not raise an "not-supported-file-format" error?"
    - Answer: "Sounds reasonable, find somebody to make a PR to `bids-validator`"
1. "Why is the `scans.tsv`placed on the `session` level in the file hierachry as opposed to within each `session` firectory?"
    - Answer: "Probably historical reasons" (we don't know right now)

### agenda 2: Derivatives

1. Should we join BEP017 (connectivity) to also define connectivity derivatives for MEEG?
    - Consensus: Yes ... let's try to specify together ... if it turns out to be impossible, we can split off
1. The derivatives for MEEG (BEP021) have been stagnating a bit because efforts were directed at making the raw specs for eeg/ieeg happen
    - this will change in the coming months
    - we want to make a survey aimed at finding out what most researchers need specified (e.g., annotations, epochs, ICA, ...)
    - based on this, we will adopt a "data-driven 80-20" rule, that is: based on the survey, try to implement in a brief amount of time the bulk of derivatives that most researchers need
    - We will make a call for contributions to BEP021 and distribute it ...
        - on Github
        - on the Google Mailing list
        - on neurostars.org ... and all other channels we can think of
    - this call for contributions will make it clear that BIDS is user-driven and that everyone can chime in and enrich the process of fleshing out the derivatives specification
    - regarding annotations: use JSON sidecards and the HED column in accompanying TSV files extensively ... and then see where it's not sufficient to capture all richness of annotations
---

@TimVanMourik can you please re-open this issue? I think it'd improve the visibility of it.

**Comment by sappelhoff** [comment]
regarding "general feedback" point 1, see: https://github.com/bids-standard/bids-validator/issues/786

**Comment by TimVanMourik** [comment]
Closing this discussion as an issue, but feel free to add more content, links, or documents (PR) to document what's been discussed!
